### ISSUE TITLE
Angular-cli Support? Documentation?

### ISSUE THREAD

**Issue by arahmanali** [haoliangyu/ngx-leaflet-starter#37]
Is there any hope to expect for angular-cli support or proper documentation any time soon?
TIA

**Comment by haoliangyu** [comment]
@arahmanali Thank you for suggesting it.

I understand that adding tools like [angular-cli](https://github.com/angular/angular-cli) can be very helpful. But people have different tastes for tools and the choice depends on certain needs, so I don't hope to build this starter project around a certain tool. I believe this starter is flexible enough for any development tool. If you prefer angular-cli, please feel free to fork this repo and integrate angular-cli. I will be very happy to add the link and tell people about your work.

As for `proper documentation`, can you give me a hint on what you want to know?

**Comment by arahmanali** [comment]
@haoliangyu Thank you for response,
i will definitely give it a try to integrate it with angular-cli, as far as proper documentation is concern i came across with this package https://github.com/Asymmetrik/angular2-leaflet and found a proper **Table of Contents** so i thought i should share.

**Comment by haoliangyu** [comment]
Yeah, angular2-leaflet indeed has much more detailed documentation. I will find time to gradually populate the README.md. At the meanwhile, if you have any question, please feel free to open an issue.
