### ISSUE TITLE
How to use this library

### ISSUE THREAD

**Issue by theCrab** [haoliangyu/ngx-leaflet-starter#38]
Hi. I am new to Angular 2/4. I am trying to use this lib but I can't figure out how to. Sounds dump but, well am a noob right now. Any help :|

**Comment by haoliangyu** [comment]
@theCrab Please let me know if I misunderstand you.

This project is not a reusable library, but a demo project. I develop this for two purposes:
* to help people (you and me) to understand how to use Angular and Leaflet together
* to provide a starter template for people who is developer an Angular map application

If you are using this project to learn Angular or Leaflet, I would suggest you to set up this application locally (see [guides](https://github.com/haoliangyu/ngx-leaflet-starter#how-to-start)), check its features, and read the code to see how I implemented it.

If you are looking for a reusable Angular 4 leaflet component, you may try [ui-leaflet-ng2](https://github.com/angular-ui/ui-leaflet-ng2) or [ngx.leaflet.component](https://github.com/elasticrash/ngx.leaflet.component).
