### ISSUE TITLE
Integration of cartoDB.js and layers

### ISSUE THREAD

**Issue by johan--** [haoliangyu/ngx-leaflet-starter#40]
Hi - this is perhaps not quite an issue with the library, but rather with integration of cartodb layers.

The issue relates to the usage of the cartodb.js library that's loaded directly into index.html (as used by my seed application)

This is the script :
  <script src="http://libs.cartocdn.com/cartodb.js/v3/3.15/cartodb.js"></script>

Using it in map.service.ts is problematic:
    import * as cartodb from 'cartodb';

And this is the result:
Module not found: Error: Can't resolve 'cartodb'

Any pointers would be appreciated.

Thanks!

**Comment by haoliangyu** [comment]
While you use the `import` keyword, the `webpack` will by default search the library in your `node_modules`. As it cannot find `cartodb` at your local folder, it throws the error.

To let `webpack` work with a library from external source, you need to add the library into `webpack` using the [externals](https://webpack.js.org/configuration/externals/#externals) configuration option.

**Comment by johan--** [comment]
Thanks for the feedback, I'll try the externals option.  I've managed to get it working by using this in the relevant component:

declare var cartodb: any;

One more question on this topic: how does one include bower components in conjunction with node modules (without adding an external entry for each)?

**Comment by haoliangyu** [comment]
I am glad that you figure it out.

I have not tried bower + webpack. But you should be able to use bower & webpack2 without specifying any external entry: see [this thread](https://github.com/webpack/webpack/issues/2324).
