### ISSUE TITLE
Plugins

### ISSUE THREAD

**Issue by pcrombach** [haoliangyu/ngx-leaflet-starter#41]
I have an Ionic 1 app with a lot of leaflet plugins used. I want to switch to Ionic 3. I don't know how to implement leaflet plugins and use them. Can you help me?

**Comment by haoliangyu** [comment]
Hey @pcrombach,

I have no experience on Ionic so I may lack a proper understanding. Here is my interpretation

> I have an Ionic 1 app with a lot of leaflet plugins used

My app was originally written in JavaScript and used Leaflet plugins, which were also written in JavaScript.

> I want to switch to Ionic 3.

Now it is going to be a TypeScript project.

> I don't know how to implement leaflet plugins and use them.

Your question: How do I use Leaflet plugin developed in JavaScript in a TypeScript project?

Using JavaScript Leaflet plugin is like using other 3rd library not written in JavaScript. By importing the type definition file, you can use the plugin in a TypeScript project like it's JavaScript.

Here are the steps:
1. install and import the Leaflet plugin
2. go to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) to check if someone has already created the type definition file. If yes, you can install  the type definition with

```
npm install @types/leaflet-plugin-name
```

3. if not found, you need to create the type definition by yourself (see [doc](http://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html)). Usually, you just need to write a minimal definition like [this](https://github.com/haoliangyu/ngx-leaflet-starter/blob/master/public_src/typings/leaflet.vectorgrid.d.ts). Then import the type definition with

```
<reference path="path/to/leaflet-plugin.d.ts"/>
```
4. With the type definition, TypeScript is able recognize the Leaflet plugin and allows you to use it.

I have done [the similar thing](https://github.com/haoliangyu/ngx-leaflet-starter/commit/c2391f859202390f37324e21609b0b39766be6fa) to use [leaflet.vectorgrid](https://github.com/Leaflet/Leaflet.VectorGrid) in this project.

**Comment by pcrombach** [comment]
Hi. You re great. Thank you for this reply. I understand what you are saying here. It's now midnight here. The next couple of days I don't have time to try out you tips. But I can't hardly wait. After a few days I'll give it a try and for all inspect the way how you did it with the leaflet.vectorgrid plugin. You'll hear about this from me.

Thanks again.

Verstuurd vanaf mijn iPad
