### ISSUE TITLE
Grey Tiles

### ISSUE THREAD

**Issue by marct83** [haoliangyu/ngx-leaflet-starter#43]
Hi. I'm trying to use this as an example and put this into a project I'm working on.

Generally....what are some of the possible issues when all the tiles aren't rendering and are staying grey? Some load some don't.

**Comment by haoliangyu** [comment]
I would like to know more details to figure out the reason:
* Is there any error message or HTTP request failure?
* Do the tile images align correctly on the screen?
* Are the geographic features drawn correctly?

I am not sure you are able to provide me some code examples or screenshots. If you can, it will definitely help.
