### ISSUE TITLE
Refresh of Angular app on every mouse move (the pointermove event)

### ISSUE THREAD

**Issue by sashuk** [haoliangyu/ngx-leaflet-starter#44]
Hello! First I would like to thank you for the package, it does a great job!
Now about the issue - I've noticed that whenever map is loaded in the application as a regular component, all other component are reloaded with every mouse move. The reason is that the map package is applying the `pointermove`, `pointerup`, `pointerdown` and `pointercancel` events to the `<body>` tag, so something is triggered and the Angular app is refreshed.

Steps to recreate:
1. Create and register the following component
```
import {Component} from "@angular/core";

@Component({
    selector: "test",
    template: `<h1>{{componentValue}}</h1>`
})
export class TestComponent {
    _componentValue: String = 'lalala';
    constructor() { }
    set componentValue(value) {}
    get componentValue() {
        console.log('Somebody is getting the value');
        return this._componentValue;
    }
}
```
2. Add it somewhere in the `app.component.html`

3. Load the app and see that on every mouse move the `TestComponent` is redrawn (the `get componentValue()` is called)

4. If we remove the map, nothing happend on the mouse move.

I am afraid that this could be the issue with the map itself, maybe you've encountered such problem before?

**Comment by haoliangyu** [comment]
@sashuk Thanks for reporting this issue and the steps! This issue looks strange to me so I cannot tell what happens there. But refreshing at every mouse move looks bad though I did not even notice it during the development 🤔 I will find some time this week to take a look.

**Comment by sashuk** [comment]
@haoliangyu Hello! Sorry, but it seems to be the map issue indeed (https://github.com/Asymmetrik/ngx-leaflet/issues/110), so I think the issue can be closed.
