### ISSUE TITLE
How to integrate with KML in leaflet-plugins?

### ISSUE THREAD

**Issue by bomberblue07** [haoliangyu/ngx-leaflet-starter#46]
Hi @haoliangyu thank you for this starter guide, it was a great help with my project. I am trying to integrate with the [KML plugin in leaflet-plugins](https://github.com/shramov/leaflet-plugins/blob/master/layer/vector/KML.js) but I'm not having much luck. I tried following [your plugin guide](https://haoliangyu.github.io/2017/01/25/Using-an-untyped-Leaflet-plugin-in-your-TypeSccript-project/) but it didn't seem to work for the structure of this plugin.

Do you have any guidance or advice?

**Comment by haoliangyu** [comment]
@bomberblue07 

This plugin has a quite different structure than the leaflet-vectorgrid. I am afraid I don't have any very precise advice on it right now. In general, I would recommend searching the type definition of other plugins in the [DefinitlyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/find/master) to see if there is anything similar. For example, [this file](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/leaflet-gpx/index.d.ts#L17) could be useful as it is also extending the FeatureGroup class.

**Comment by bomberblue07** [comment]
@haoliangyu 

I just need to construct a KML object and then add it to my map so following that example you gave me, I created [this rough typings file](https://gist.github.com/bomberblue07/83316873906e32ce82c553e69af7e09f) and while it caused no compilation errors, I get a runtime error when I call the constructor that's something along the lines of "WEBPACK_MODULE is not a constructor"

I use Angular CLI to build by project. I think the problem is the compilation from TypeScript to JavaScript loses the KML plugin in translation. I add the KML.js script to my scripts array in .angular-cli.json after leaflet.js. Am I doing something wrong that has nothing to do with typings?

**Comment by bomberblue07** [comment]
I was eventually able to integrate the plugin with the latest leaflet and typings by directly importing the javascript file and calling the constructor untyped. Not ideal, but it works for now.
