### ISSUE TITLE
Airport layer for other layers

### ISSUE THREAD

**Issue by mrinalusp** [haoliangyu/ngx-leaflet-starter#52]
Hello,

The airport geojson doesnt work for other maps. Any reason why?

Thank YOU!

**Comment by haoliangyu** [comment]
I am pretty sure the geojson is valid as both GitHub and QGIS can read it. Can you provide more details on what `other maps` are and how you work with them?

**Comment by mrinalusp** [comment]
When i select the ESRI map and then click on Airport Toggle , the icons dont show up. It looks like the icons are there but they are getting hidden and not able to overlay on ESRI maps. 

![image](https://user-images.githubusercontent.com/18711965/36506496-cff47406-1724-11e8-8215-afa0a28b2a7b.png)

**Comment by haoliangyu** [comment]
This is an interesting finding. I did not anticipate the vector-tile layer could be covered by the base map. Since I only use the basic way to create layer and change base maps, I suspect there is an issue with the vectorgrid library. But I am not sure at this moment.

**Comment by haoliangyu** [comment]
I find the reason. It is a z-index issue. See https://github.com/Leaflet/Leaflet.VectorGrid/issues/154
