### ISSUE TITLE
Airport layer not working

### ISSUE THREAD

**Issue by bagage** [haoliangyu/ngx-leaflet-starter#58]
When toggling it on:

> ERROR TypeError: "tile is null"
_tileReady	
	http://localhost:4200/vendor.js:129379:7invokeTask
	http://localhost:4200/polyfills.js:2743:17onInvokeTask
	http://localhost:4200/vendor.js:57374:24invokeTask
	http://localhost:4200/polyfills.js:2742:17runTask
	http://localhost:4200/polyfills.js:2510:28invokeTask
	http://localhost:4200/polyfills.js:2818:24invoke
	http://localhost:4200/polyfills.js:2807:28timer
	http://localhost:4200/polyfills.js:4376:17

**Comment by bagage** [comment]
Upstream bug in vectorgrid: https://github.com/Leaflet/Leaflet.VectorGrid/issues/175

Fix: `yarn add leaflet@==1.3.1`

**Comment by ashleysommer** [comment]
Upstream bug in leaflet (which in turn was causing that mentioned bug in leaflet.vectorgrid) has been fixed with the release of leaflet 1.3.4 today.
Use `yarn add leaflet@^1.3.4` to fix it.

**Comment by haoliangyu** [comment]
Thanks for reporting this issue. This issue should have been fixed.
